import {SeedData} from "@/interfaces";

export const initialData: SeedData = {
    products: [
        {
            name: "Norin the Wary",
            title: "Norin the Wary",
            description: "Norin the Wary",
            slug: "Norin the Wary",
            setCode: "SLD",
            setName: "Secret Lair Drop",
            collectorNumber: "827",
            foil: "foil",
            rarity: "rare",
            quantity: 3,
            manaBoxID: 95269,
            image: "3d89c9be-2489-47e4-8e53-f980c82442b4",
            price: 14.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Ashling, Flame Dancer",
            title: "Ashling, Flame Dancer",
            description: "Ashling, Flame Dancer",
            slug: "Ashling, Flame Dancer",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "115",
            foil: "normal",
            rarity: "mythic",
            quantity: 3,
            manaBoxID: 94417,
            image: "40463be5-89e2-410b-9a4b-770f70d14293",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Maddening Hex",
            title: "Maddening Hex",
            description: "Maddening Hex",
            slug: "Maddening Hex",
            setCode: "SPG",
            setName: "Special Guests",
            collectorNumber: "70",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 98873,
            image: "95b9be27-5abe-4341-b100-eba5c7854601",
            price: 6.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Legion Loyalist",
            title: "Legion Loyalist",
            description: "Legion Loyalist",
            slug: "Legion Loyalist",
            setCode: "GTC",
            setName: "Gatecrash",
            collectorNumber: "97",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 16727,
            image: "b47f639e-4635-4c26-bb2a-4925f0582c21",
            price: 9.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Blazing Shoal",
            title: "Blazing Shoal",
            description: "Blazing Shoal",
            slug: "Blazing Shoal",
            setCode: "PLST",
            setName: "The List",
            collectorNumber: "BOK-96",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 66846,
            image: "f719c6e2-271d-410e-8610-4171767ab887",
            price: 5.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Ral, Monsoon Mage // Ral, Leyline Prodigy",
            title: "Ral, Monsoon Mage // Ral, Leyline Prodigy",
            description: "Ral, Monsoon Mage // Ral, Leyline Prodigy",
            slug: "Ral, Monsoon Mage // Ral, Leyline Prodigy",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "247",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 94422,
            image: "438d8a26-ddc9-4829-8aff-22d6af6575cf",
            price: 5.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Crackle with Power",
            title: "Crackle with Power",
            description: "Crackle with Power",
            slug: "Crackle with Power",
            setCode: "PSTX",
            setName: "Strixhaven: School of Mages Promos",
            collectorNumber: "95p",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 59119,
            image: "4ee02acc-5f11-442d-9355-384806203a3b",
            price: 12.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Dracogenesis",
            title: "Dracogenesis",
            description: "Dracogenesis",
            slug: "Dracogenesis",
            setCode: "TDM",
            setName: "Tarkir: Dragonstorm",
            collectorNumber: "105",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 104241,
            image: "0d5674f9-22b2-45f9-902d-4fd245485c60",
            price: 8.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Twinflame",
            title: "Twinflame",
            description: "Twinflame",
            slug: "Twinflame",
            setCode: "2X2",
            setName: "Double Masters 2022",
            collectorNumber: "129",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 70505,
            image: "ccaa7c17-55e7-44e4-a965-182f63f32c72",
            price: 9.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Surly Badgersaur",
            title: "Surly Badgersaur",
            description: "Surly Badgersaur",
            slug: "Surly Badgersaur",
            setCode: "C20",
            setName: "Commander 2020",
            collectorNumber: "57",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 50361,
            image: "7ba507e2-fe5e-4947-aada-20184aa09700",
            price: 10.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Reforge the Soul",
            title: "Reforge the Soul",
            description: "Reforge the Soul",
            slug: "Reforge the Soul",
            setCode: "C16",
            setName: "Commander 2016",
            collectorNumber: "132",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 7222,
            image: "25ab0711-a06b-4c4c-a49e-d951915d918c",
            price: 5.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Malignus",
            title: "Malignus",
            description: "Malignus",
            slug: "Malignus",
            setCode: "PLST",
            setName: "The List",
            collectorNumber: "AVR-148",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 63916,
            image: "ca52fe78-8840-487b-93f6-14198423d55f",
            price: 8.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Goryo's Vengeance",
            title: "Goryo's Vengeance",
            description: "Goryo's Vengeance",
            slug: "Goryo's Vengeance",
            setCode: "DSC",
            setName: "Duskmourn: House of Horror Commander",
            collectorNumber: "372",
            foil: "foil",
            rarity: "mythic",
            quantity: 2,
            manaBoxID: 98616,
            image: "2d451d81-cc5c-4d9b-8825-c6865edcf84a",
            price: 8.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Damnation",
            title: "Damnation",
            description: "Damnation",
            slug: "Damnation",
            setCode: "SPG",
            setName: "Special Guests",
            collectorNumber: "68",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 98652,
            image: "93376e64-1086-43e1-9326-8cbe9f850233",
            price: 29.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Midnight Banshee",
            title: "Midnight Banshee",
            description: "Midnight Banshee",
            slug: "Midnight Banshee",
            setCode: "MM2",
            setName: "Modern Masters 2015",
            collectorNumber: "86",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 11131,
            image: "c7da8f15-ea21-46fd-b24f-f8af4d5d5f1d",
            price: 8.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Rottenmouth Viper",
            title: "Rottenmouth Viper",
            description: "Rottenmouth Viper",
            slug: "Rottenmouth Viper",
            setCode: "BLB",
            setName: "Bloomburrow",
            collectorNumber: "107",
            foil: "normal",
            rarity: "mythic",
            quantity: 3,
            manaBoxID: 96058,
            image: "735e79b1-a3a9-4ddf-8bbc-f756c8a0452b",
            price: 7.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Enduring Tenacity",
            title: "Enduring Tenacity",
            description: "Enduring Tenacity",
            slug: "Enduring Tenacity",
            setCode: "DSK",
            setName: "Duskmourn: House of Horror",
            collectorNumber: "95",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 95615,
            image: "d5756d4b-3068-412c-8643-880d3459151e",
            price: 6.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Death's Shadow",
            title: "Death's Shadow",
            description: "Death's Shadow",
            slug: "Death's Shadow",
            setCode: "SCH",
            setName: "Store Championships",
            collectorNumber: "40",
            foil: "foil",
            rarity: "rare",
            quantity: 3,
            manaBoxID: 106322,
            image: "7c6fa517-5570-470a-88ca-d7afcb5fb475",
            price: 18.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Living End",
            title: "Living End",
            description: "Living End",
            slug: "Living End",
            setCode: "SLP",
            setName: "Secret Lair Showdown",
            collectorNumber: "30",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 103761,
            image: "8e6043b1-ac82-40d1-aada-de911e0b58c0",
            price: 8.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Dauthi Voidwalker",
            title: "Dauthi Voidwalker",
            description: "Dauthi Voidwalker",
            slug: "Dauthi Voidwalker",
            setCode: "MH2",
            setName: "Modern Horizons 2",
            collectorNumber: "397",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 59634,
            image: "7d54f0dd-5d27-483b-8af9-92a1c5a785f2",
            price: 14.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Black Market Connections",
            title: "Black Market Connections",
            description: "Black Market Connections",
            slug: "Black Market Connections",
            setCode: "CLB",
            setName: "Commander Legends: Battle for Baldur's Gate",
            collectorNumber: "669",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 69664,
            image: "d13cb0d3-3452-4c1f-81ec-024b4c45bbad",
            price: 20.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Unstoppable Slasher",
            title: "Unstoppable Slasher",
            description: "Unstoppable Slasher",
            slug: "Unstoppable Slasher",
            setCode: "DSK",
            setName: "Duskmourn: House of Horror",
            collectorNumber: "119",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 98912,
            image: "c78da035-6b5b-4136-9ab6-f622b64fdc54",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Cursecloth Wrappings",
            title: "Cursecloth Wrappings",
            description: "Cursecloth Wrappings",
            slug: "Cursecloth Wrappings",
            setCode: "DFT",
            setName: "Aetherdrift",
            collectorNumber: "400",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 103262,
            image: "c5280941-bcda-4ac7-97d1-db02c7a18ef9",
            price: 12.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Bolas's Citadel",
            title: "Bolas's Citadel",
            description: "Bolas's Citadel",
            slug: "Bolas's Citadel",
            setCode: "WAR",
            setName: "War of the Spark",
            collectorNumber: "79",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 44325,
            image: "d2124603-d20e-40eb-97f0-a66323397ac2",
            price: 9.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Force of Despair",
            title: "Force of Despair",
            description: "Force of Despair",
            slug: "Force of Despair",
            setCode: "SLP",
            setName: "Secret Lair Showdown",
            collectorNumber: "29",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 99993,
            image: "c298d757-6d9d-4d33-86b6-e198299859be",
            price: 12.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Heroic Intervention",
            title: "Heroic Intervention",
            description: "Heroic Intervention",
            slug: "Heroic Intervention",
            setCode: "WHO",
            setName: "Doctor Who",
            collectorNumber: "233",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 87883,
            image: "cd11d822-51c7-41dd-8f78-718d884019e8",
            price: 13.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Innkeeper's Talent",
            title: "Innkeeper's Talent",
            description: "Innkeeper's Talent",
            slug: "Innkeeper's Talent",
            setCode: "PBLB",
            setName: "Bloomburrow Promos",
            collectorNumber: "180p",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 97134,
            image: "fa35cd95-0904-4bf8-a4e8-62fd2aca716a",
            price: 18.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Walk-In Closet // Forgotten Cellar",
            title: "Walk-In Closet // Forgotten Cellar",
            description: "Walk-In Closet // Forgotten Cellar",
            slug: "Walk-In Closet // Forgotten Cellar",
            setCode: "DSK",
            setName: "Duskmourn: House of Horror",
            collectorNumber: "205",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 99047,
            image: "0adcd4e5-d542-4293-8774-ace2305ef820",
            price: 10.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Ancient Greenwarden",
            title: "Ancient Greenwarden",
            description: "Ancient Greenwarden",
            slug: "Ancient Greenwarden",
            setCode: "ZNR",
            setName: "Zendikar Rising",
            collectorNumber: "178",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 54783,
            image: "dfe08e59-fdc4-436f-b05c-6ad386c46310",
            price: 15.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Railway Brawler",
            title: "Railway Brawler",
            description: "Railway Brawler",
            slug: "Railway Brawler",
            setCode: "OTJ",
            setName: "Outlaws of Thunder Junction",
            collectorNumber: "175",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 93285,
            image: "9ec1f76f-f21d-4f06-8c02-be6745183348",
            price: 9.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Case of the Locked Hothouse",
            title: "Case of the Locked Hothouse",
            description: "Case of the Locked Hothouse",
            slug: "Case of the Locked Hothouse",
            setCode: "MKM",
            setName: "Murders at Karlov Manor",
            collectorNumber: "155",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 90640,
            image: "0929a1bd-e35c-4ca5-8c8c-dd304cf4b830",
            price: 5.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Collected Company",
            title: "Collected Company",
            description: "Collected Company",
            slug: "Collected Company",
            setCode: "DTK",
            setName: "Dragons of Tarkir",
            collectorNumber: "177",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 11637,
            image: "cfa7b456-7e83-4587-a875-9b35fde318c2",
            price: 3.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Multani, Yavimaya's Avatar",
            title: "Multani, Yavimaya's Avatar",
            description: "Multani, Yavimaya's Avatar",
            slug: "Multani, Yavimaya's Avatar",
            setCode: "MB2",
            setName: "Mystery Booster 2",
            collectorNumber: "248",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 96786,
            image: "565ab4c8-abf3-4b74-9f4b-882f73322a49",
            price: 37.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Awaken the Woods",
            title: "Awaken the Woods",
            description: "Awaken the Woods",
            slug: "Awaken the Woods",
            setCode: "PBRO",
            setName: "The Brothers' War Promos",
            collectorNumber: "170p",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 76924,
            image: "23508f42-aba6-4c74-9a41-5ccd1e9b1c87",
            price: 27.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Life from the Loam",
            title: "Life from the Loam",
            description: "Life from the Loam",
            slug: "Life from the Loam",
            setCode: "RAV",
            setName: "Ravnica: City of Guilds",
            collectorNumber: "172",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 27838,
            image: "7ac16d09-8bc7-407c-a757-666f4707bc90",
            price: 10.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Nature's Rhythm",
            title: "Nature's Rhythm",
            description: "Nature's Rhythm",
            slug: "Nature's Rhythm",
            setCode: "TDM",
            setName: "Tarkir: Dragonstorm",
            collectorNumber: "150",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 104460,
            image: "1397d904-c51d-451e-8505-7f3118acc1f6",
            price: 4.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Grist, Voracious Larva // Grist, the Plague Swarm",
            title: "Grist, Voracious Larva // Grist, the Plague Swarm",
            description: "Grist, Voracious Larva // Grist, the Plague Swarm",
            slug: "Grist, Voracious Larva // Grist, the Plague Swarm",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "446",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 94370,
            image: "201eb299-4e89-432c-9bdc-7e862ef20d92",
            price: 5.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Kodama of the West Tree",
            title: "Kodama of the West Tree",
            description: "Kodama of the West Tree",
            slug: "Kodama of the West Tree",
            setCode: "PNEO",
            setName: "Kamigawa: Neon Dynasty Promos",
            collectorNumber: "199p",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 67246,
            image: "795f0206-2c5f-4f34-9bff-1793c643a09b",
            price: 21.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Ocelot Pride",
            title: "Ocelot Pride",
            description: "Ocelot Pride",
            slug: "Ocelot Pride",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "38",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 94771,
            image: "89cf6f57-230f-497e-a14e-ad1e8737fd42",
            price: 49.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Kataki, War's Wage",
            title: "Kataki, War's Wage",
            description: "Kataki, War's Wage",
            slug: "Kataki, War's Wage",
            setCode: "MB2",
            setName: "Mystery Booster 2",
            collectorNumber: "148",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 96714,
            image: "2fe21296-7e04-410d-b441-aed64451682f",
            price: 27.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Guide of Souls",
            title: "Guide of Souls",
            description: "Guide of Souls",
            slug: "Guide of Souls",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "29",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 94504,
            image: "76c3cad2-1e25-4abe-878d-9194de6fcc27",
            price: 5.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Voice of Victory",
            title: "Voice of Victory",
            description: "Voice of Victory",
            slug: "Voice of Victory",
            setCode: "TDM",
            setName: "Tarkir: Dragonstorm",
            collectorNumber: "33",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 104377,
            image: "ec3de5f4-bb55-4ab9-995f-f3e0dc22c1bb",
            price: 19.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Hero of Bladehold",
            title: "Hero of Bladehold",
            description: "Hero of Bladehold",
            slug: "Hero of Bladehold",
            setCode: "PMBS",
            setName: "Mirrodin Besieged Promos",
            collectorNumber: "8★",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 20146,
            image: "8829efa0-498a-43ca-91aa-f9caeeafe298",
            price: 3.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Hallowed Haunting",
            title: "Hallowed Haunting",
            description: "Hallowed Haunting",
            slug: "Hallowed Haunting",
            setCode: "PVOW",
            setName: "Innistrad: Crimson Vow Promos",
            collectorNumber: "17p",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 77664,
            image: "987ab975-4d22-4e39-855b-255c1ee6adba",
            price: 7.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Recruiter of the Guard",
            title: "Recruiter of the Guard",
            description: "Recruiter of the Guard",
            slug: "Recruiter of the Guard",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "266",
            foil: "normal",
            rarity: "mythic",
            quantity: 3,
            manaBoxID: 94535,
            image: "8e4c6ba1-1abc-478f-9b7c-97e9e3c92fb0",
            price: 9.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Flawless Maneuver",
            title: "Flawless Maneuver",
            description: "Flawless Maneuver",
            slug: "Flawless Maneuver",
            setCode: "C20",
            setName: "Commander 2020",
            collectorNumber: "26",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 50392,
            image: "c972abe6-c732-4745-bde4-8b51698f05be",
            price: 22.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Rune-Tail, Kitsune Ascendant // Rune-Tail's Essence",
            title: "Rune-Tail, Kitsune Ascendant // Rune-Tail's Essence",
            description: "Rune-Tail, Kitsune Ascendant // Rune-Tail's Essence",
            slug: "Rune-Tail, Kitsune Ascendant // Rune-Tail's Essence",
            setCode: "PLST",
            setName: "The List",
            collectorNumber: "SOK-27",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 47526,
            image: "1f1c4bf1-2a9a-4802-af28-4e7c3dae97ee",
            price: 5.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Akroma's Will",
            title: "Akroma's Will",
            description: "Akroma's Will",
            slug: "Akroma's Will",
            setCode: "LCC",
            setName: "The Lost Caverns of Ixalan Commander",
            collectorNumber: "125",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 88540,
            image: "608cdbdb-6f7e-438a-bab0-0e7782435f0f",
            price: 15.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Aven Interrupter",
            title: "Aven Interrupter",
            description: "Aven Interrupter",
            slug: "Aven Interrupter",
            setCode: "OTJ",
            setName: "Outlaws of Thunder Junction",
            collectorNumber: "4",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 93360,
            image: "d3ca43a4-d194-440f-8099-f1fa103a108d",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Stonehewer Giant",
            title: "Stonehewer Giant",
            description: "Stonehewer Giant",
            slug: "Stonehewer Giant",
            setCode: "PLST",
            setName: "The List",
            collectorNumber: "2XM-32",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 59951,
            image: "da9aa48f-c960-4148-b03a-026a027e436b",
            price: 7.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Venser's Journal",
            title: "Venser's Journal",
            description: "Venser's Journal",
            slug: "Venser's Journal",
            setCode: "SOM",
            setName: "Scars of Mirrodin",
            collectorNumber: "220",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 20812,
            image: "2763643d-5b53-49d0-bc3d-5626bf00f3f4",
            price: 18.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Monument to Endurance",
            title: "Monument to Endurance",
            description: "Monument to Endurance",
            slug: "Monument to Endurance",
            setCode: "DFT",
            setName: "Aetherdrift",
            collectorNumber: "237",
            foil: "normal",
            rarity: "rare",
            quantity: 2,
            manaBoxID: 103640,
            image: "d21433ba-0a14-42bc-ad0b-a4ef823a3295",
            price: 9.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Jeweled Lotus",
            title: "Jeweled Lotus",
            description: "Jeweled Lotus",
            slug: "Jeweled Lotus",
            setCode: "CMM",
            setName: "Commander Masters",
            collectorNumber: "396",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 80429,
            image: "d7183700-6941-4a3d-a581-4f33bea795e9",
            price: 34.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Hex Parasite",
            title: "Hex Parasite",
            description: "Hex Parasite",
            slug: "Hex Parasite",
            setCode: "NPH",
            setName: "New Phyrexia",
            collectorNumber: "137",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 19748,
            image: "43502078-5349-4e29-8e7d-277654a9a71e",
            price: 11.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Multiversal Passage",
            title: "Multiversal Passage",
            description: "Multiversal Passage",
            slug: "Multiversal Passage",
            setCode: "SPM",
            setName: "Marvel's Spider-Man",
            collectorNumber: "180",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 107889,
            image: "f5fb426a-5618-4dd4-9c51-0cc847be8c1d",
            price: 12.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Susur Secundi, Void Altar",
            title: "Susur Secundi, Void Altar",
            description: "Susur Secundi, Void Altar",
            slug: "Susur Secundi, Void Altar",
            setCode: "EOE",
            setName: "Edge of Eternities",
            collectorNumber: "259",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 107126,
            image: "aefb8c0d-2bc6-4bec-851e-0137b4abfb22",
            price: 12.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Inkmoth Nexus",
            title: "Inkmoth Nexus",
            description: "Inkmoth Nexus",
            slug: "Inkmoth Nexus",
            setCode: "EOS",
            setName: "Edge of Eternities: Stellar Sights",
            collectorNumber: "20",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 107268,
            image: "4c65f0c0-e771-4236-a3aa-02a0104eb4bc",
            price: 9.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Sliver Hive",
            title: "Sliver Hive",
            description: "Sliver Hive",
            slug: "Sliver Hive",
            setCode: "PF25",
            setName: "MagicFest 2025",
            collectorNumber: "7",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 105773,
            image: "1445b61c-a105-4d4c-be42-5cbf7cd43f89",
            price: 17.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Ugin's Labyrinth",
            title: "Ugin's Labyrinth",
            description: "Ugin's Labyrinth",
            slug: "Ugin's Labyrinth",
            setCode: "PMH3",
            setName: "Modern Horizons 3 Promos",
            collectorNumber: "233p",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 108320,
            image: "6579cb87-70fe-43ff-8a1a-f7fb89da6aaa",
            price: 32.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Three Tree City",
            title: "Three Tree City",
            description: "Three Tree City",
            slug: "Three Tree City",
            setCode: "BLB",
            setName: "Bloomburrow",
            collectorNumber: "260",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 95785,
            image: "56f88a48-cced-4a9d-8c19-e4f105f0d8a2",
            price: 24.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Hushwood Verge",
            title: "Hushwood Verge",
            description: "Hushwood Verge",
            slug: "Hushwood Verge",
            setCode: "DSK",
            setName: "Duskmourn: House of Horror",
            collectorNumber: "261",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 98751,
            image: "ec288d76-c1f5-471b-8a53-504f88469c1b",
            price: 8.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Shifting Woodland",
            title: "Shifting Woodland",
            description: "Shifting Woodland",
            slug: "Shifting Woodland",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "228",
            foil: "normal",
            rarity: "rare",
            quantity: 2,
            manaBoxID: 94327,
            image: "059164e1-894d-4586-9800-e60d6fbd6eb6",
            price: 9.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Emeria, the Sky Ruin",
            title: "Emeria, the Sky Ruin",
            description: "Emeria, the Sky Ruin",
            slug: "Emeria, the Sky Ruin",
            setCode: "ZEN",
            setName: "Zendikar",
            collectorNumber: "213",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 22411,
            image: "fdf6016e-71e7-4339-80f9-78e9aa44c54b",
            price: 27.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Arena of Glory",
            title: "Arena of Glory",
            description: "Arena of Glory",
            slug: "Arena of Glory",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "215",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 94820,
            image: "dd148edc-9e43-41aa-bb50-f912115d3e72",
            price: 14.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Sunbillow Verge",
            title: "Sunbillow Verge",
            description: "Sunbillow Verge",
            slug: "Sunbillow Verge",
            setCode: "DFT",
            setName: "Aetherdrift",
            collectorNumber: "373",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 103268,
            image: "c92a7ca5-a25b-4888-a319-6e176ab4d0ce",
            price: 14.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Lush Portico",
            title: "Lush Portico",
            description: "Lush Portico",
            slug: "Lush Portico",
            setCode: "MKM",
            setName: "Murders at Karlov Manor",
            collectorNumber: "263",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 91179,
            image: "c17816e8-28b1-4295-a637-efb0e5c18873",
            price: 11.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Commercial District",
            title: "Commercial District",
            description: "Commercial District",
            slug: "Commercial District",
            setCode: "MKM",
            setName: "Murders at Karlov Manor",
            collectorNumber: "259",
            foil: "normal",
            rarity: "rare",
            quantity: 2,
            manaBoxID: 91168,
            image: "bf220c06-3cce-4bdd-aa58-83940c223e9c",
            price: 9.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Stomping Ground",
            title: "Stomping Ground",
            description: "Stomping Ground",
            slug: "Stomping Ground",
            setCode: "RVR",
            setName: "Ravnica Remastered",
            collectorNumber: "289",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 89781,
            image: "872301b2-b6e7-4972-a479-66a7e304c1d3",
            price: 16.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Cavern of Souls",
            title: "Cavern of Souls",
            description: "Cavern of Souls",
            slug: "Cavern of Souls",
            setCode: "2X2",
            setName: "Double Masters 2022",
            collectorNumber: "320",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 70572,
            image: "e697ea72-e10e-4fed-be8f-8c6455cc3fc8",
            price: 44.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Undercity Sewers",
            title: "Undercity Sewers",
            description: "Undercity Sewers",
            slug: "Undercity Sewers",
            setCode: "MKM",
            setName: "Murders at Karlov Manor",
            collectorNumber: "270",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 90747,
            image: "2b5801fb-2026-4f25-98bc-ebb2f99684b9",
            price: 27.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Kiora, the Rising Tide",
            title: "Kiora, the Rising Tide",
            description: "Kiora, the Rising Tide",
            slug: "Kiora, the Rising Tide",
            setCode: "FDN",
            setName: "Foundations",
            collectorNumber: "309",
            foil: "foil",
            rarity: "rare",
            quantity: 2,
            manaBoxID: 100543,
            image: "5a123794-096f-4d01-bfd4-1d23f22608f7",
            price: 6.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Mirror Room // Fractured Realm",
            title: "Mirror Room // Fractured Realm",
            description: "Mirror Room // Fractured Realm",
            slug: "Mirror Room // Fractured Realm",
            setCode: "DSK",
            setName: "Duskmourn: House of Horror",
            collectorNumber: "337",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 98677,
            image: "f0c32b23-0586-4ac2-9304-d90b4636e7ae",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Nezahal, Primal Tide",
            title: "Nezahal, Primal Tide",
            description: "Nezahal, Primal Tide",
            slug: "Nezahal, Primal Tide",
            setCode: "PLST",
            setName: "The List",
            collectorNumber: "RIX-45",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 89100,
            image: "7545164c-4b39-4a1a-b2d4-975967ca1fb5",
            price: 16.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Murktide Regent",
            title: "Murktide Regent",
            description: "Murktide Regent",
            slug: "Murktide Regent",
            setCode: "PMH2",
            setName: "Modern Horizons 2 Promos",
            collectorNumber: "52p",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 92990,
            image: "dda68e02-45d4-4dee-b257-c4ae7e47eaeb",
            price: 16.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Murktide Regent",
            title: "Murktide Regent",
            description: "Murktide Regent",
            slug: "Murktide Regent",
            setCode: "MH2",
            setName: "Modern Horizons 2",
            collectorNumber: "52",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 59439,
            image: "20c4aae1-7665-4df7-bd51-a1d95bf8a17d",
            price: 9.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Rhystic Study",
            title: "Rhystic Study",
            description: "Rhystic Study",
            slug: "Rhystic Study",
            setCode: "WOT",
            setName: "Wilds of Eldraine: Enchanting Tales",
            collectorNumber: "25",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 85233,
            image: "043b2d30-a40f-4d47-933b-80544512f9c2",
            price: 79.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Echo of Eons",
            title: "Echo of Eons",
            description: "Echo of Eons",
            slug: "Echo of Eons",
            setCode: "MH1",
            setName: "Modern Horizons",
            collectorNumber: "46",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 44888,
            image: "ff590af2-2d6c-4f16-a9b8-1a6dab6e9ad5",
            price: 15.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Overlord of the Floodpits",
            title: "Overlord of the Floodpits",
            description: "Overlord of the Floodpits",
            slug: "Overlord of the Floodpits",
            setCode: "DSK",
            setName: "Duskmourn: House of Horror",
            collectorNumber: "68",
            foil: "normal",
            rarity: "mythic",
            quantity: 2,
            manaBoxID: 98711,
            image: "5fca5de8-9cda-4370-9f72-4462f8cfd696",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Vesuvan Duplimancy",
            title: "Vesuvan Duplimancy",
            description: "Vesuvan Duplimancy",
            slug: "Vesuvan Duplimancy",
            setCode: "DMU",
            setName: "Dominaria United",
            collectorNumber: "73",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 71632,
            image: "9a2119bc-a377-4156-89d4-56e7b5b494a8",
            price: 4.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Omniscience",
            title: "Omniscience",
            description: "Omniscience",
            slug: "Omniscience",
            setCode: "FDN",
            setName: "Foundations",
            collectorNumber: "161",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 95588,
            image: "d33d91d0-1506-45e4-9def-975bf901815e",
            price: 8.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Phantasmal Image",
            title: "Phantasmal Image",
            description: "Phantasmal Image",
            slug: "Phantasmal Image",
            setCode: "M12",
            setName: "Magic 2012",
            collectorNumber: "72",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 19195,
            image: "98e7bf8f-dba7-4005-8cee-634c9153931d",
            price: 5.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Jace's Archivist",
            title: "Jace's Archivist",
            description: "Jace's Archivist",
            slug: "Jace's Archivist",
            setCode: "C15",
            setName: "Commander 2015",
            collectorNumber: "95",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 9941,
            image: "3c21df8e-a24f-4ce1-aa8a-1467f9f9423a",
            price: 11.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Displacer Kitten",
            title: "Displacer Kitten",
            description: "Displacer Kitten",
            slug: "Displacer Kitten",
            setCode: "CLB",
            setName: "Commander Legends: Battle for Baldur's Gate",
            collectorNumber: "560",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 69180,
            image: "9a53e8fc-bfd2-4866-a61c-f3204b0a98bf",
            price: 42.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Tamiyo, Inquisitive Student // Tamiyo, Seasoned Scholar",
            title: "Tamiyo, Inquisitive Student // Tamiyo, Seasoned Scholar",
            description: "Tamiyo, Inquisitive Student // Tamiyo, Seasoned Scholar",
            slug: "Tamiyo, Inquisitive Student // Tamiyo, Seasoned Scholar",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "242",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 94392,
            image: "2a717b98-cdac-416d-bf6c-f6b6638e65d1",
            price: 37.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Mayhem Devil",
            title: "Mayhem Devil",
            description: "Mayhem Devil",
            slug: "Mayhem Devil",
            setCode: "SLP",
            setName: "Secret Lair Showdown",
            collectorNumber: "28",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 99994,
            image: "e7c570c4-6637-4269-a59f-6448d85dfc50",
            price: 5.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Squall, SeeD Mercenary",
            title: "Squall, SeeD Mercenary",
            description: "Squall, SeeD Mercenary",
            slug: "Squall, SeeD Mercenary",
            setCode: "PSS5",
            setName: "FIN Standard Showdown",
            collectorNumber: "2",
            foil: "foil",
            rarity: "rare",
            quantity: 5,
            manaBoxID: 106324,
            image: "076af4bd-1b74-4cf3-b6a0-8ec17d5b0e26",
            price: 44.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "The Locust God",
            title: "The Locust God",
            description: "The Locust God",
            slug: "The Locust God",
            setCode: "C20",
            setName: "Commander 2020",
            collectorNumber: "219",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 50199,
            image: "87f6aaba-ad2d-41ea-8d07-21c67d384aa0",
            price: 6.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Flame of Anor",
            title: "Flame of Anor",
            description: "Flame of Anor",
            slug: "Flame of Anor",
            setCode: "LTR",
            setName: "The Lord of the Rings: Tales of Middle-earth",
            collectorNumber: "203",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 82828,
            image: "04779a7e-b453-48b9-b392-6d6fd0b8d283",
            price: 7.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Talion, the Kindly Lord",
            title: "Talion, the Kindly Lord",
            description: "Talion, the Kindly Lord",
            slug: "Talion, the Kindly Lord",
            setCode: "WOE",
            setName: "Wilds of Eldraine",
            collectorNumber: "215",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 85447,
            image: "62a6b452-c796-45c6-b4d1-0ae3d675e38e",
            price: 10.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Betor, Kin to All",
            title: "Betor, Kin to All",
            description: "Betor, Kin to All",
            slug: "Betor, Kin to All",
            setCode: "PTDM",
            setName: "Tarkir: Dragonstorm Promos",
            collectorNumber: "172p",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 105251,
            image: "5006a96e-718f-45c0-b8f0-1d2ad714511c",
            price: 6.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Experiment Kraj",
            title: "Experiment Kraj",
            description: "Experiment Kraj",
            slug: "Experiment Kraj",
            setCode: "DIS",
            setName: "Dissension",
            collectorNumber: "110",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 27315,
            image: "cb7f42a1-0996-4799-ad3a-9525c8e31343",
            price: 8.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Gishath, Sun's Avatar",
            title: "Gishath, Sun's Avatar",
            description: "Gishath, Sun's Avatar",
            slug: "Gishath, Sun's Avatar",
            setCode: "PLCI",
            setName: "The Lost Caverns of Ixalan Promos",
            collectorNumber: "229p",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 89462,
            image: "c1c1624b-8ac5-451a-becc-b13fb6605af9",
            price: 10.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Riptide Gearhulk",
            title: "Riptide Gearhulk",
            description: "Riptide Gearhulk",
            slug: "Riptide Gearhulk",
            setCode: "PDFT",
            setName: "Aetherdrift Promos",
            collectorNumber: "219p",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 103841,
            image: "1db8c49d-94c3-4ecb-a641-9e7b28b76c5e",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Riptide Gearhulk",
            title: "Riptide Gearhulk",
            description: "Riptide Gearhulk",
            slug: "Riptide Gearhulk",
            setCode: "DFT",
            setName: "Aetherdrift",
            collectorNumber: "219",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 103487,
            image: "44bfb0f7-18ca-4f6e-ba64-92120010456e",
            price: 3.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Brightglass Gearhulk",
            title: "Brightglass Gearhulk",
            description: "Brightglass Gearhulk",
            slug: "Brightglass Gearhulk",
            setCode: "DFT",
            setName: "Aetherdrift",
            collectorNumber: "191",
            foil: "normal",
            rarity: "mythic",
            quantity: 3,
            manaBoxID: 100066,
            image: "3dea5b45-925c-4732-8e9d-fa8232792736",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Loading Zone",
            title: "Loading Zone",
            description: "Loading Zone",
            slug: "Loading Zone",
            setCode: "PEOE",
            setName: "Edge of Eternities Promos",
            collectorNumber: "196s",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 107930,
            image: "3445216a-4ffe-42fc-b1a0-6c9501d8d566",
            price: 3.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Stormsplitter",
            title: "Stormsplitter",
            description: "Stormsplitter",
            slug: "Stormsplitter",
            setCode: "PBLB",
            setName: "Bloomburrow Promos",
            collectorNumber: "154s",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 96925,
            image: "96a2bb96-d152-4030-b486-91e69846ceb9",
            price: 5.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Virtue of Courage // Embereth Blaze",
            title: "Virtue of Courage // Embereth Blaze",
            description: "Virtue of Courage // Embereth Blaze",
            slug: "Virtue of Courage // Embereth Blaze",
            setCode: "PWOE",
            setName: "Wilds of Eldraine Promos",
            collectorNumber: "157p",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 86245,
            image: "c9bdcfe6-671e-4475-a48d-bfe45d8a5e01",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Explore",
            title: "Explore",
            description: "Explore",
            slug: "Explore",
            setCode: "SLP",
            setName: "Secret Lair Showdown",
            collectorNumber: "12",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 88140,
            image: "d6ff821f-d60a-497e-9809-20fd0a80594c",
            price: null,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Gwenom, Remorseless",
            title: "Gwenom, Remorseless",
            description: "Gwenom, Remorseless",
            slug: "Gwenom, Remorseless",
            setCode: "PSPM",
            setName: "Marvel's Spider-Man Promos",
            collectorNumber: "56s",
            foil: "foil",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 109028,
            image: "1f013b42-05d5-43f5-b20b-177ca52c0587",
            price: 24.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Darkness",
            title: "Darkness",
            description: "Darkness",
            slug: "Darkness",
            setCode: "SPG",
            setName: "Special Guests",
            collectorNumber: "124",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 107578,
            image: "ef4c2c08-0a4d-4588-bc35-078da7120937",
            price: 9.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Sami, Wildcat Captain",
            title: "Sami, Wildcat Captain",
            description: "Sami, Wildcat Captain",
            slug: "Sami, Wildcat Captain",
            setCode: "EOE",
            setName: "Edge of Eternities",
            collectorNumber: "301",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 107098,
            image: "968fb6d4-f4b9-4c8d-b296-fea002a8c003",
            price: 5.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Koma, Cosmos Serpent",
            title: "Koma, Cosmos Serpent",
            description: "Koma, Cosmos Serpent",
            slug: "Koma, Cosmos Serpent",
            setCode: "PKHM",
            setName: "Kaldheim Promos",
            collectorNumber: "221p",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 57371,
            image: "682cdd7e-31ff-4789-9d0d-ad43581c7621",
            price: 4.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Carnage, Crimson Chaos",
            title: "Carnage, Crimson Chaos",
            description: "Carnage, Crimson Chaos",
            slug: "Carnage, Crimson Chaos",
            setCode: "SPM",
            setName: "Marvel's Spider-Man",
            collectorNumber: "227",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 108450,
            image: "67a7cbe7-cf78-4a3f-86c3-00d5ab93361e",
            price: 3.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Riptide Gearhulk",
            title: "Riptide Gearhulk",
            description: "Riptide Gearhulk",
            slug: "Riptide Gearhulk",
            setCode: "DFT",
            setName: "Aetherdrift",
            collectorNumber: "219",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 103487,
            image: "44bfb0f7-18ca-4f6e-ba64-92120010456e",
            price: 3.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Assassin's Trophy",
            title: "Assassin's Trophy",
            description: "Assassin's Trophy",
            slug: "Assassin's Trophy",
            setCode: "MKM",
            setName: "Murders at Karlov Manor",
            collectorNumber: "187",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 91290,
            image: "ed6c7d29-71b4-4134-b591-5598f479d592",
            price: 4.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Pinnacle Emissary",
            title: "Pinnacle Emissary",
            description: "Pinnacle Emissary",
            slug: "Pinnacle Emissary",
            setCode: "PEOE",
            setName: "Edge of Eternities Promos",
            collectorNumber: "223s",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 107952,
            image: "6b0e32e9-78a5-48f4-a0b7-0c49f5f3a118",
            price: 5.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Crawlspace",
            title: "Crawlspace",
            description: "Crawlspace",
            slug: "Crawlspace",
            setCode: "DMR",
            setName: "Dominaria Remastered",
            collectorNumber: "217",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 77921,
            image: "5b8e092a-610d-4cea-bb92-65e01954b5c4",
            price: 6.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Smuggler's Surprise",
            title: "Smuggler's Surprise",
            description: "Smuggler's Surprise",
            slug: "Smuggler's Surprise",
            setCode: "OTJ",
            setName: "Outlaws of Thunder Junction",
            collectorNumber: "180",
            foil: "normal",
            rarity: "rare",
            quantity: 2,
            manaBoxID: 93400,
            image: "e7fbb489-e2b5-4278-8162-86802cf124d8",
            price: 6.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Nexus of Fate",
            title: "Nexus of Fate",
            description: "Nexus of Fate",
            slug: "Nexus of Fate",
            setCode: "SPG",
            setName: "Special Guests",
            collectorNumber: "122",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 107431,
            image: "506dab4a-9b63-4f9f-897f-7bb06fea871f",
            price: 5.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Abhorrent Oculus",
            title: "Abhorrent Oculus",
            description: "Abhorrent Oculus",
            slug: "Abhorrent Oculus",
            setCode: "DSK",
            setName: "Duskmourn: House of Horror",
            collectorNumber: "344",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 98977,
            image: "5f89402a-ef5c-47c1-8cef-f40920f98fac",
            price: 23.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Consult the Star Charts",
            title: "Consult the Star Charts",
            description: "Consult the Star Charts",
            slug: "Consult the Star Charts",
            setCode: "EOE",
            setName: "Edge of Eternities",
            collectorNumber: "51",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 107113,
            image: "a16a6555-2e3a-4587-aacd-0307d696b26c",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Approach of the Second Sun",
            title: "Approach of the Second Sun",
            description: "Approach of the Second Sun",
            slug: "Approach of the Second Sun",
            setCode: "AKH",
            setName: "Amonkhet",
            collectorNumber: "4",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 5681,
            image: "fdf59a6e-7708-45a1-884d-d12e9f7b9ed9",
            price: 5.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Forest",
            title: "Forest",
            description: "Forest",
            slug: "Forest",
            setCode: "ODY",
            setName: "Odyssey",
            collectorNumber: "349",
            foil: "foil",
            rarity: "common",
            quantity: 1,
            manaBoxID: 31828,
            image: "318b15ea-80b9-48df-b010-aa1aabcf51ea",
            price: 12.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Mountain",
            title: "Mountain",
            description: "Mountain",
            slug: "Mountain",
            setCode: "ONS",
            setName: "Onslaught",
            collectorNumber: "343",
            foil: "foil",
            rarity: "common",
            quantity: 1,
            manaBoxID: 30960,
            image: "05f9bdca-0d54-46c7-b803-9083dfc9ee24",
            price: 3.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Marvin, Murderous Mimic",
            title: "Marvin, Murderous Mimic",
            description: "Marvin, Murderous Mimic",
            slug: "Marvin, Murderous Mimic",
            setCode: "DSK",
            setName: "Duskmourn: House of Horror",
            collectorNumber: "253",
            foil: "normal",
            rarity: "rare",
            quantity: 6,
            manaBoxID: 98981,
            image: "66898970-b99b-48f2-9240-68c301c95500",
            price: 4.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Worldwalker Helm",
            title: "Worldwalker Helm",
            description: "Worldwalker Helm",
            slug: "Worldwalker Helm",
            setCode: "PBIG",
            setName: "The Big Score Promos",
            collectorNumber: "7p",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 108319,
            image: "54a5deb8-7439-40b2-84bc-95dbde805d22",
            price: 7.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Springheart Nantuko",
            title: "Springheart Nantuko",
            description: "Springheart Nantuko",
            slug: "Springheart Nantuko",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "171",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 94453,
            image: "54a3ea87-005e-4985-b2a5-21711d0b71c0",
            price: 7.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Fomori Vault",
            title: "Fomori Vault",
            description: "Fomori Vault",
            slug: "Fomori Vault",
            setCode: "PBIG",
            setName: "The Big Score Promos",
            collectorNumber: "29p",
            foil: "normal",
            rarity: "mythic",
            quantity: 1,
            manaBoxID: 108323,
            image: "bf5c3883-ca22-4850-9721-d1acb16acbd8",
            price: 16.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Flare of Malice",
            title: "Flare of Malice",
            description: "Flare of Malice",
            slug: "Flare of Malice",
            setCode: "MH3",
            setName: "Modern Horizons 3",
            collectorNumber: "95",
            foil: "normal",
            rarity: "rare",
            quantity: 3,
            manaBoxID: 94360,
            image: "19efb9ce-62eb-4cbf-b01e-979f3fd09ba6",
            price: 4.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Marvin, Murderous Mimic",
            title: "Marvin, Murderous Mimic",
            description: "Marvin, Murderous Mimic",
            slug: "Marvin, Murderous Mimic",
            setCode: "PDSK",
            setName: "Duskmourn: House of Horror Promos",
            collectorNumber: "253p",
            foil: "normal",
            rarity: "rare",
            quantity: 5,
            manaBoxID: 99930,
            image: "d15e8cef-1a92-4883-8f78-e27b40e618ac",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Swamp",
            title: "Swamp",
            description: "Swamp",
            slug: "Swamp",
            setCode: "NEO",
            setName: "Kamigawa: Neon Dynasty",
            collectorNumber: "298",
            foil: "normal",
            rarity: "common",
            quantity: 1,
            manaBoxID: 66486,
            image: "57ef531e-2a8f-4d40-b509-92e3a86b2257",
            price: 4.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Unstoppable Slasher",
            title: "Unstoppable Slasher",
            description: "Unstoppable Slasher",
            slug: "Unstoppable Slasher",
            setCode: "DSK",
            setName: "Duskmourn: House of Horror",
            collectorNumber: "312",
            foil: "normal",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 98767,
            image: "0a30a301-8e87-46e7-89aa-cd55b1a14420",
            price: 5.49,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        },
        {
            name: "Yedora, Grave Gardener",
            title: "Yedora, Grave Gardener",
            description: "Yedora, Grave Gardener",
            slug: "Yedora, Grave Gardener",
            setCode: "MUL",
            setName: "Multiverse Legends",
            collectorNumber: "160",
            foil: "foil",
            rarity: "rare",
            quantity: 1,
            manaBoxID: 81888,
            image: "b2e3a335-56ec-4e9d-8171-c436783666d2",
            price: 3.99,
            condition: "near_mint",
            language: "en",
            type: "MTG",
        }
    ]
}